# https://youtu.be/ky-24RvI57s?t=7533


import csv
#Here user imput are stored in format of csv file give name of file it will apend user data in that file
#Autogenerated_file is the name we wanted for our file to get and has extension type as CSV

Khola=open("Autogenerated_file.csv","a")

#User Name and Number will be stored in our desired file

a=input("Name:")
b=input("Number:")

#csv writer is same as method which write the content that provides and saves in format declared earlier
Likho=csv.writer(Khola)
Likho.writerow([a,b])

Khola.close()



#HERE WE ALSO HAD AND ALTERNATIVE WAY OF DOING ABOVE THINGS AND THAT IS BY WITH
# import csv
# a=input("Enter Name:")
# b=input("Enter Number:")

#with means with opening the desired file provided name do as follow in Khola which is variable name for file
# with open("Autogenerated.csv","a") as Khola:
#     Likho=csv.writer(Khola)
#     Likho.writerow([a,b])